import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {pathToFileURL,fileURLToPath} from 'node:url';
import {registerHooks} from 'node:module';
import ts from 'typescript';
import {JSDOM} from 'jsdom';
import React,{act} from 'react';
import {createRoot} from 'react-dom/client';
const hooks=registerHooks({resolve(specifier,context,next){if(specifier.startsWith('@/'))return {url:pathToFileURL(resolve(specifier.slice(2)+'.ts')).href,shortCircuit:true};return next(specifier,context)},load(url,context,next){if(url.endsWith('.tsx'))return {format:'module',source:ts.transpileModule(readFileSync(fileURLToPath(url),'utf8'),{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2020}}).outputText,shortCircuit:true};return next(url,context)}});
const dom=new JSDOM('<div id="root"></div>',{url:'http://localhost'});
const saved=new Map();for(const [key,value] of Object.entries({window:dom.window,document:dom.window.document,FormData:dom.window.FormData,IS_REACT_ACT_ENVIRONMENT:true})){saved.set(key,Object.getOwnPropertyDescriptor(globalThis,key));Object.defineProperty(globalThis,key,{value,writable:true,configurable:true})}
const originalFetch=globalThis.fetch;let root;
try{
 const {AdminRecords}=await import('../components/erp/admin-records.tsx');
 const a='11111111-1111-4111-8111-111111111111',b='22222222-2222-4222-8222-222222222222';
 const db={auth:{getSession:async()=>({data:{session:{access_token:'test'}}})}};
 let pending,detailSignal;const requests=[];
 globalThis.fetch=async(_url,init)=>{const r=JSON.parse(init.body);requests.push(r);if(r.operation.endsWith('_detail')){detailSignal=init.signal;return new Promise(resolve=>{pending=resolve})}return Response.json({data:{rows:r.company===a?[{id:a,business_id:a,description:'Pedido de teste',currency:'BRL'}]:[],count:r.company===a?1:0}})};
 root=createRoot(document.getElementById('root'));
 const mount=company=>act(async()=>{root.render(React.createElement(AdminRecords,{key:company,db,company,companyName:company===a?'Empresa A':'Empresa B'}))});
 const click=label=>act(async()=>{const button=[...document.querySelectorAll('button')].find(e=>e.textContent===label);assert.ok(button,label);button.click()});
 await mount(a);
 await act(async()=>{document.querySelector('[name=id]').value=a;document.querySelector('[name=actor]').value=b;document.querySelector('form').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}))});
 assert.equal(requests.at(-1).filters.id,a);assert.equal(requests.at(-1).filters.actor,b);assert.match(document.querySelector('.adm-audit-applied').textContent,/Autor:/);
 document.querySelector('[name=id]').value='';document.querySelector('[name=actor]').value='';
 await act(async()=>{document.querySelector('select[name=operation]').value='orders';document.querySelector('form').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}))});
 await click('Ver campos');assert.equal(requests.at(-1).operation,'order_detail');assert.equal(requests.at(-1).filters.id,a);
 await act(async()=>{pending(Response.json({data:{id:a,business_id:a,currency:'BRL',items:[{id:b,name:'Peça premium',quantity:2,price:50,fulfilled:1,total:100}],fulfillments:[],titles:[],fulfillment_items:[{id:b,fulfillment_id:a,name:'Item entregue',quantity:1,amount:50,warehouse_name:'Depósito principal',reversed_at:'2026-10-07T12:00:00Z',reason:'Devolução documentada'}],stock_movements:[{id:b,source_id:a,delta:-1,balance:9}],payments:[]}}))});
 assert.match(document.body.textContent,/Peça premium/);assert.match(document.body.textContent,/Itens do pedido · 1/);assert.match(document.body.textContent,/Itens por atendimento · 1/);assert.match(document.body.textContent,/Movimentos de estoque vinculados · 1/);assert.match(document.body.textContent,/Devolução documentada/);assert.match(document.body.textContent,/Depósito principal/);
 await click('Fechar campos');await click('Ver campos');const stale=pending;
 await mount(b);assert.equal(detailSignal.aborted,true);
 await act(async()=>{stale(Response.json({data:{id:a,business_id:a,description:'VAZAMENTO ANTIGO',items:[]}}))});
 assert.ok(!document.body.textContent.includes('VAZAMENTO ANTIGO'));assert.ok(!document.body.textContent.includes('Peça premium'));assert.match(document.body.textContent,/Empresa B/);
 await mount(a);await act(async()=>{document.querySelector('select[name=operation]').value='titles';document.querySelector('form').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}))});await click('Ver campos');
 assert.equal(requests.at(-1).operation,'title_detail');await act(async()=>{pending(Response.json({data:{id:a,business_id:a,currency:'BRL',payments:[{id:b,amount:50,reversed_at:'2026-09-28T12:00:00Z',reason:'Estorno de teste'}]}}))});
 assert.match(document.body.textContent,/Pagamentos e estornos · 1/);assert.match(document.body.textContent,/Estorno de teste/);
 await click('Fechar campos');await click('Ver campos');await act(async()=>{pending(Response.json({data:{id:a,business_id:b,payments:[{amount:999}]}}))});
 assert.match(document.querySelector('[role=alert]').textContent,/não corresponde/);assert.ok(!document.body.textContent.includes('999'));
 await act(async()=>root.render(null));
 const edits=[];let failOnce=true;
 globalThis.fetch=async(_url,init)=>{const body=JSON.parse(init.body);if(init.method==='PATCH'){edits.push(body);if(failOnce){failOnce=false;return Response.json({error:'Resposta indisponível; repita a revisão.'},{status:503})}return Response.json({data:{id:a,version:2,correlation:body.key}})}return Response.json({data:{rows:[{id:a,business_id:a,name:'Peça original',category:'Peças',cost:10,price:20,record_version:1}],count:1}})};
 await mount(a);await click('Ver campos');await click('Corrigir dados cadastrais');
 const correctionForm=document.querySelector('[aria-label="Correção de produto"] form');
 correctionForm.querySelector('[name=name]').value='Peça corrigida';correctionForm.querySelector('[name=reason]').value='Correção do nome cadastrado pelo operador';
 await act(async()=>correctionForm.dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true})));
 assert.equal(edits.length,0);assert.match(document.body.textContent,/Confira antes de salvar/);assert.match(document.body.textContent,/Peça original/);assert.match(document.body.textContent,/Peça corrigida/);
 await click('Confirmar correção');assert.match(document.querySelector('[role=alert]').textContent,/Resposta indisponível/);
 await click('Confirmar correção');assert.equal(edits.length,2);assert.equal(edits[0].key,edits[1].key);assert.deepEqual(edits[0].data.patch,{name:'Peça corrigida'});assert.equal(edits[0].data.version,1);assert.match(document.body.textContent,/Alteração registrada/);
 await click('Ver campos');await click('Inativar produto');
 const statusForm=document.querySelector('[aria-label="Correção de produto"] form');statusForm.querySelector('[name=reason]').value='Produto descontinuado pela administração';
 await act(async()=>statusForm.dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true})));
 assert.match(document.body.textContent,/Situação/);await click('Confirmar situação');assert.equal(edits.at(-1).operation,'admin.product.archive');assert.equal(edits.at(-1).data.patch,undefined);
 let historyPending,historySignal;const previousFetch=globalThis.fetch;
 globalThis.fetch=async(url,init)=>{const value=JSON.parse(init.body);if(value.operation==='record_history'){assert.equal(value.filters.id,a);historySignal=init.signal;return new Promise(resolve=>{historyPending=resolve})}return previousFetch(url,init)};
 await click('Ver campos');await click('Histórico do registro');
 const historyData={company:a,entity:a,upper:'2026-10-03T00:00:00Z',next_cursor:null,rows:[{id:'9007199254740999',audit_key:'tenant:00009007199254740999',source:'tenant',occurred_at:'2026-10-02T12:00:00Z',actor_id:b,subject_id:a,action:'admin.product.correct',reason:'Correção registrada no histórico',result:'success',correlation_id:b,before_data:{name:'Nome anterior auditado'},after_data:{name:'Nome posterior auditado'}}]};
 await act(async()=>historyPending(Response.json({data:historyData})));
 assert.match(document.body.textContent,/Nome anterior auditado/);assert.match(document.body.textContent,/Nome posterior auditado/);assert.match(document.body.textContent,/9007199254740999/);
 await click('Atualizar desde o início');const staleHistory=historyPending;
 await mount(b);assert.equal(historySignal.aborted,true);await act(async()=>staleHistory(Response.json({data:historyData})));assert.ok(!document.body.textContent.includes('Nome anterior auditado'));
 await act(async()=>root.render(null));const cancellations=[];let cancelFail=true;
 globalThis.fetch=async(_url,init)=>{const v=JSON.parse(init.body);if(init.method==='PATCH'){cancellations.push(v);if(cancelFail){cancelFail=false;return Response.json({error:'Cancelamento não confirmado; repita a revisão.'},{status:503})}return Response.json({data:{id:a,version:3,correlation:v.key}})}if(v.operation.endsWith('_detail'))return Response.json({data:{id:a,business_id:a,items:[],titles:[],fulfillments:[]}});return Response.json({data:{rows:[{id:a,business_id:a,status:'confirmed',record_version:2,description:'Pedido a cancelar'}],count:1}})};
 await mount(a);await act(async()=>{document.querySelector('select[name=operation]').value='orders';document.querySelector('form').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}))});await click('Ver campos');await click('Cancelar pedido');
 const cancelForm=document.querySelector('[aria-label="Cancelamento administrativo"] form');cancelForm.querySelector('[name=reason]').value='Pedido duplicado identificado pela administração';await act(async()=>cancelForm.dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true})));
 assert.equal(cancellations.length,0);assert.match(document.body.textContent,/O cancelamento também cancela os títulos/);await click('Confirmar cancelamento');await click('Confirmar cancelamento');assert.equal(cancellations.length,2);assert.equal(cancellations[0].key,cancellations[1].key);assert.equal(cancellations[0].operation,'admin.order.cancel');assert.equal(cancellations[0].data.version,2);assert.match(document.body.textContent,/Cancelamento registrado/);
 await act(async()=>root.render(null));const reversals=[];let reversalFails=true;
 globalThis.fetch=async(_url,init)=>{const v=JSON.parse(init.body);if(init.method==='PATCH'){reversals.push(v);if(reversalFails){reversalFails=false;return Response.json({error:'Resposta indisponível.'},{status:503})}return Response.json({data:{id:b,version:2,correlation:v.key}})}if(v.operation.endsWith('_detail'))return Response.json({data:{id:a,business_id:a,currency:'BRL',payments:[{id:b,amount:5,record_version:1,reversed_at:null}]}});return Response.json({data:{rows:[{id:a,business_id:a,description:'Título com pagamento',paid:5,amount:20}],count:1}})};
 await mount(a);await act(async()=>{document.querySelector('select[name=operation]').value='titles';document.querySelector('form').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}))});await click('Ver campos');await click('Estornar pagamento');
 const reversalForm=document.querySelector('[aria-label="Estorno administrativo"] form');reversalForm.querySelector('[name=reason]').value='Pagamento duplicado identificado pela administração';await act(async()=>reversalForm.dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true})));
 assert.equal(reversals.length,0);assert.match(document.body.textContent,/não envia dinheiro/);await click('Confirmar estorno');await click('Confirmar estorno');assert.equal(reversals.length,2);assert.equal(reversals[0].key,reversals[1].key);assert.equal(reversals[0].operation,'admin.payment.reverse');assert.equal(reversals[0].data.id,b);assert.equal(reversals[0].data.amount,undefined);assert.match(document.body.textContent,/Operação financeira registrada/);
 console.log('PASS: detalhes, isolamento de contexto, histórico, revisão de correção/cancelamento/estorno e repetição com mesma chave após falha de rede. DOM e rede simulados.');
}finally{
 if(root)await act(async()=>root.unmount());globalThis.fetch=originalFetch;hooks.deregister();dom.window.close();for(const [key,descriptor] of saved){if(descriptor)Object.defineProperty(globalThis,key,descriptor);else delete globalThis[key]}
}
