import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import Module from 'manifold-3d';
import {operate} from '../public/3d/operations.mjs';
import {read3MF,write3MF,bounds} from '../lib/three-mf.ts';
import {unzipSync,zipSync,strFromU8,strToU8} from 'fflate';
globalThis.DOMParser=new JSDOM('').window.DOMParser;
const M=await Module();M.setup();
const [box]=operate(M,{action:'generate',shape:'box',size:[80,60,35],wall:2});
assert.equal(box.volume,80*60*35-76*56*33);
const split=operate(M,{action:'split',mesh:box,axis:2,cut:17.5});
assert.equal(split.length,2);assert.ok(Math.abs(split[0].volume+split[1].volume-box.volume)<.001);
for(const half of split)assert.ok(operate(M,{action:'inspect',mesh:half})[0].volume>0);
assert.throws(()=>operate(M,{action:'split',mesh:box,axis:2,cut:100}));
assert.throws(()=>operate(M,{action:'inspect',mesh:{...box,triangles:box.triangles.slice(3)}}));
assert.throws(()=>operate(M,{action:'generate',shape:'box',size:[80,60,35],wall:50}));
const [vase]=operate(M,{action:'generate',shape:'vase',size:[60,80,90],wall:2});
const [smooth]=operate(M,{action:'smooth',mesh:vase,angle:45});assert.ok(smooth.triangles.length>vase.triangles.length);assert.ok(smooth.volume>0);
const data=write3MF([{id:'1',name:'Caixa & <teste>',mesh:box}]);
const roundtrip=read3MF(data.buffer);assert.equal(roundtrip[0].name,'Caixa & <teste>');assert.deepEqual(bounds(roundtrip[0].mesh).size,[80,60,35]);
const files=unzipSync(data);const inner=strFromU8(files['3D/3dmodel.model']);
files['3D/Objects/part.model']=strToU8(inner);
files['3D/3dmodel.model']=strToU8('<model unit="millimeter" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02" xmlns:p="http://schemas.microsoft.com/3dmanufacturing/production/2015/06"><resources><object id="2"><components><component p:path="/3D/Objects/part.model" objectid="1" transform="1 0 0 0 1 0 0 0 1 10 20 30"/></components></object></resources><build><item objectid="2"/></build></model>');
const component=read3MF(zipSync(files).buffer);assert.deepEqual(bounds(component[0].mesh).min,[10,20,30]);
files['3D/Objects/part.model']=strToU8(inner.replace('unit="millimeter"','unit="inch"'));assert.throws(()=>read3MF(zipSync(files).buffer));
files['3D/Objects/part.model']=strToU8(inner);files['3D/3dmodel.model']=strToU8(strFromU8(files['3D/3dmodel.model']).replace('p:path="/3D/Objects/part.model" objectid="1"','objectid="2"'));assert.throws(()=>read3MF(zipSync(files).buffer));
const inches=unzipSync(data);inches['3D/3dmodel.model']=strToU8(inner.replace('unit="millimeter"','unit="inch"'));assert.ok(Math.abs(bounds(read3MF(zipSync(inches).buffer)[0].mesh).size[0]-2032)<.001);
console.log('PASS: solid generator, capped split/volume conservation, invalid meshes and dimensions, smoothing, 3MF roundtrip, production components/transforms, unit conversion and cyclic reference rejection.');
