-- Run after operations + access migrations in a transaction that is rolled back.
do $$
declare u uuid:=gen_random_uuid(); peer uuid:=gen_random_uuid(); outsider uuid:=gen_random_uuid(); sid uuid:=gen_random_uuid(); psid uuid:=gen_random_uuid(); osid uuid:=gen_random_uuid();
 b uuid; second_b uuid; product uuid; payload jsonb; result jsonb; denied boolean; cache_key uuid:=gen_random_uuid(); claims jsonb;
begin
 insert into auth.users(id,email) values(u,'access-owner-'||u||'@example.invalid'),(peer,'access-peer-'||peer||'@example.invalid'),(outsider,'access-outsider-'||outsider||'@example.invalid');
 insert into auth.sessions(id,user_id,created_at,aal) values(sid,u,now(),'aal1'),(psid,peer,now(),'aal1'),(osid,outsider,now(),'aal1');
 claims:=jsonb_build_object('sub',u,'session_id',sid,'exp',floor(extract(epoch from now()+interval '1 hour')),'iat',floor(extract(epoch from now())),'aal','aal1');
 perform set_config('request.jwt.claim.sub',u::text,true);perform set_config('request.jwt.claims',claims::text,true);
 b:=(public.erp_command(null,'business.save','{"name":"Políticas A","model":"printing"}',gen_random_uuid())->>'id')::uuid;
 second_b:=(public.erp_command(null,'business.save','{"name":"Políticas B","model":"printing"}',gen_random_uuid())->>'id')::uuid;
 payload:='{"name":"Peça protegida","unit":"un","item_type":"finished","cost":1,"price":2,"currency":"BRL","stock":0}';
 product:=(public.erp_command(b,'product.save',payload,cache_key)->>'id')::uuid;
 insert into erp_control.memberships(company_id,user_id,role) values(b,peer,'read');
 perform set_config('request.jwt.claim.sub',peer::text,true);perform set_config('request.jwt.claims',(claims||jsonb_build_object('sub',peer,'session_id',psid))::text,true);
 result:=public.erp_read(b,'products');
 if result->'rows'->0->>'id'<>product::text then raise exception 'Members do not see the same records';end if;
 denied:=false;begin perform public.erp_read(second_b,'products');exception when insufficient_privilege then denied:=true;end;
 if not denied then raise exception 'Company identifier swap allowed';end if;
 update erp_control.memberships set active=false where company_id=b and user_id=peer;
 denied:=false;begin perform public.erp_read(b,'products');exception when insufficient_privilege then denied:=true;end;
 if not denied then raise exception 'Unlinked membership remains authorized';end if;
 if not exists(select 1 from public.products where id=product) then raise exception 'Unlink removed historical data';end if;
 perform set_config('request.jwt.claim.sub',u::text,true);perform set_config('request.jwt.claims',claims::text,true);
 insert into erp_control.permissions(company_id,scope,subject,module,action,allowed) values(b,'company','*','catalog','available',false),(b,'user',u::text,'catalog','create',true);
 denied:=false;begin perform public.erp_command(b,'product.save',payload,cache_key);exception when insufficient_privilege then denied:=true;end;
 if not denied then raise exception 'Idempotency result bypasses new deny policy';end if;
 denied:=false;begin perform public.erp_read(b,'products');exception when insufficient_privilege then denied:=true;end;
 if not denied then raise exception 'Disabled module readable directly';end if;
 denied:=false;begin perform public.erp_authorize(b,'catalog','read');exception when insufficient_privilege then denied:=true;end;
 if not denied then raise exception 'External endpoint authorize bypass';end if;
 if jsonb_array_length(public.erp_read(b,'lookups')->'products')<>0 then raise exception 'Disabled products leaked via lookups';end if;
 if erp_control.storage_allowed(b::text||'/test.png','product-photos','create') then raise exception 'Disabled module permits upload';end if;
 if erp_control.storage_allowed(b::text||'/test.png','product-photos','delete') then raise exception 'Disabled module permits file deletion';end if;
 delete from erp_control.permissions where company_id=b;
 insert into erp_control.permissions(company_id,scope,subject,module,action,allowed) values(b,'company','*','catalog','create',false);
 denied:=false;begin perform public.erp_command(b,'product.save',payload||jsonb_build_object('id',gen_random_uuid()),gen_random_uuid());exception when insufficient_privilege then denied:=true;end;
 if not denied then raise exception 'Client supplied UUID bypasses create policy';end if;
 delete from erp_control.permissions where company_id=b;
 insert into erp_control.permissions(company_id,scope,subject,module,action,allowed) values(b,'company','*','finance','read',false),(b,'company','*','catalog','export',false),(b,'company','*','catalog','visible',false);
 if public.erp_read(b,'overview') ? 'income' or public.erp_read(b,'lookups')->'accounts'<>'[]'::jsonb then raise exception 'Finance leaked in aggregate';end if;
 if public.erp_read(b,'permissions')->'catalog'->'visible'->>'allowed'<>'false' then raise exception 'Visibility policy not returned';end if;
 perform public.erp_read(b,'products'); -- Visibility is separate from read permission.
 denied:=false;begin perform public.erp_read(b,'products','{"export":true}');exception when insufficient_privilege then denied:=true;end;
 if not denied then raise exception 'Export permission ignored';end if;
 denied:=false;begin perform public.erp_read(b,'finance_summary','{"export":true}');exception when insufficient_privilege then denied:=true;end;
 if not denied then raise exception 'Finance summary bypassed read deny';end if;
 delete from erp_control.permissions where company_id=b;
 perform public.erp_read(b,'products','{"export":true}');
 if not exists(select 1 from erp_control.audit where actor_id=u and company_id=b and action='export.page') then raise exception 'Export not audited';end if;
 update erp_control.companies set status='suspended' where id=b;
 denied:=false;begin perform public.erp_command(b,'business.restore','{}',gen_random_uuid());exception when insufficient_privilege then denied:=true;end;
 if not denied then raise exception 'Owner bypassed company suspension via restore';end if;
 perform public.erp_read(second_b,'products');
 update erp_control.companies set status='active' where id=b;
 insert into erp_control.user_access(user_id,status) values(u,'blocked');
 denied:=false;begin perform public.erp_read(second_b,'products');exception when invalid_authorization_specification then denied:=true;end;
 if not denied then raise exception 'Global block did not revoke other companies';end if;
 delete from erp_control.user_access where user_id=u;
 denied:=false;begin perform public.erp_command(b,'invented.save','{}',gen_random_uuid());exception when insufficient_privilege then denied:=true;end;
 if not denied then raise exception 'Unknown operation permitted';end if;
 denied:=false;begin perform public.erp_authorize(b,null,'read');exception when insufficient_privilege then denied:=true;end;
 if not denied then raise exception 'Null policy module allowed';end if;
 if has_function_privilege('authenticated','erp_private.command_core(uuid,text,jsonb,uuid)','execute') or has_function_privilege('authenticated','erp_private.read_core(uuid,text,jsonb)','execute') or has_table_privilege('authenticated','public.products','select') or has_table_privilege('authenticated','public.erp_titles','select') then raise exception 'Direct path bypass';end if;
 set local role authenticated;
 result:=public.erp_read(b,'products');
 if result->'rows'->0->>'id'<>product::text then raise exception 'Authenticated RPC cannot read authorized data';end if;
 denied:=false;begin perform erp_private.read_core(b,'products','{}');exception when insufficient_privilege then denied:=true;end;
 if not denied then raise exception 'Core function callable';end if;
 reset role;
 delete from auth.sessions where id=sid;
 denied:=false;begin perform public.erp_read(b,'products');exception when invalid_authorization_specification then denied:=true;end;
 if not denied then raise exception 'Session revocation ignored by operational API';end if;
end $$;

