import type {FieldSpec} from './operation-fields';
import {str,num,today,type Row,rows} from '@/lib/operations';
const text=(key:string,label:string,required=false,value?:string):FieldSpec=>({key,label,required,value});
const number=(key:string,label:string,value:number,min=0,step='0.001'):FieldSpec=>({key,label,type:'number',value,min,step,required:true});
const select=(key:string,label:string,options:[string,string][],value?:string):FieldSpec=>({key,label,options,value,required:true});
const date=(key:string,label:string):FieldSpec=>({key,label,type:'date',value:today(),required:true});
export function fieldsFor(type:string,lookup:Row,row:Row,currency:string):FieldSpec[] {
 const options=(key:string,filter?:(r:Row)=>boolean):[string,string][]=>[['','Selecione'],...rows(lookup[key]).filter(r=>!filter||filter(r)).map(r=>[str(r.id),str(r.name)] as [string,string])];
 const active=select('active','Situação',[['true','Ativo'],['false','Inativo']],row.active===false?'false':'true');
 switch(type){
 case 'business':return [text('name','Nome do negócio',true),select('model','Atividade',[['printing','Impressão 3D'],['mechanic','Mecânica'],['food','Cozinha'],['lodging','Hospedagem'],['retail','Comércio'],['service','Serviços']]),text('contact_email','E-mail de contato'),text('phone','Telefone'),{key:'description',label:'Descrição',type:'textarea'}];
 case 'partner':return [text('name','Nome / razão social',true),text('document','Documento (opcional)'),{...text('email','E-mail'),type:'email'},text('phone','Telefone'),text('address','Endereço'),select('customer','Pode comprar de você?',[['true','Sim, cliente'],['false','Não']]),select('supplier','Pode fornecer para você?',[['false','Não'],['true','Sim, fornecedor']]),active];
 case 'warehouse':return [text('name','Nome do depósito',true),text('branch','Filial',true,'Matriz'),active];
 case 'account':return [text('name','Nome da conta',true),select('kind','Tipo',[['bank','Banco'],['cash','Caixa']]),{...text('currency','Moeda',true,currency),disabled:!!row.id},active];
 case 'terms':return [text('name','Nome da condição',true),number('installments','Número de parcelas',1,1,'1'),number('interval_days','Intervalo em dias',30,1,'1'),select('method','Forma de pagamento',[['transfer','Transferência'],['card','Cartão'],['cash','Dinheiro'],['other','Outro']]),active];
 case 'member':return [{...text('email','E-mail da conta já cadastrada',true),type:'email'},select('role','Permissão',[['read','Somente leitura'],['sales','Comercial'],['purchases','Compras'],['stock','Estoque e produção'],['finance','Financeiro'],['admin','Administrador']]),active];
 case 'title':return [text('description','Descrição do lançamento',true),select('type','Tipo',[['income','A receber'],['expense','A pagar']]),number('amount','Valor total',0,.0001,'.0001'),date('competence_date','Data de competência'),date('due_date','Primeiro vencimento'),number('installments','Parcelas mensais (até 36)',1,1,'1'),text('category','Categoria',true,'Operação')];
 case 'payment':return [number('amount','Valor a liquidar',num(row.amount)-num(row.paid),.0001,'.0001'),select('account_id','Conta financeira',options('accounts')),date('date','Data do pagamento / recebimento'),select('method','Forma',[['transfer','Transferência'],['card','Cartão'],['cash','Dinheiro'],['other','Outro']])];
 case 'stock':return [select('warehouse_id','Depósito de origem',options('warehouses'),str(row.warehouse_id)),select('mode','Tipo de movimento',[['adjust','Entrada / saída'],['inventory','Contagem de inventário'],['transfer','Transferência']]),number('quantity','Quantidade (saída: valor negativo)',0,-100000000,'.001'),select('destination_id','Destino, somente para transferência',options('warehouses')),text('reason','Motivo da movimentação',true)];
 case 'printer':return [text('name','Nome do equipamento',true),select('model','Modelo Bambu',[['A1 mini','A1 mini'],['A1','A1'],['P1S','P1S'],['P2S','P2S'],['A2 (manual)','A2 — dados manuais']]),number('nozzle','Bico (mm)',.4,.1,'.1'),number('watts','Potência média medida (W)',100),number('hourly_cost','Manutenção e depreciação / hora',0,0,'.0001'),number('maintenance_hours','Revisão a cada (horas)',500,1),active];
 case 'spool':return [text('name','Identificação da bobina',true),...(!row.id?[select('warehouse_id','Depósito',options('warehouses')),number('remaining_g','Peso líquido a atribuir (g)',1000,.001)]:[]),text('manufacturer','Fabricante'),text('material','Material',true,'PLA'),text('color','Cor / acabamento'),text('lot','Lote')];
 case 'job':return [text('name','Nome da impressão',true),select('printer_id','Impressora',options('printers')),select('spool_id','Bobina',options('spools')),number('quantity','Quantidade de peças',1,.001),number('estimated_g','Material total estimado, incluindo suportes (g)',100,.001),number('estimated_hours','Horas totais estimadas',2,.001),number('kwh_price','Tarifa de energia / kWh',.95,0,'.0001'),date('due_date','Prazo'),{...select('file_id','Arquivo 3MF (opcional)',options('files')),required:false},text('order_id','ID do pedido confirmado (opcional)'),{key:'notes',label:'Preparação e observações',type:'textarea'}];
 case 'finish':return [number('actual_g','Material total consumido (g)',num(row.estimated_g),0),number('actual_hours','Tempo real de máquina (h)',num(row.estimated_hours),0),number('good_quantity','Peças aprovadas (0 para falha)',num(row.quantity),0),select('warehouse_id','Depósito das peças prontas',options('warehouses')),{key:'notes',label:'Falhas, retrabalho e observações',type:'textarea'}];
 default:return [{key:'reason',label:'Motivo',type:'textarea',required:true}];
 }
}

