"use client";
import {useState,useRef,useEffect} from 'react';
import {Upload,Download,Scissors,Sparkles,Box,RotateCcw,Printer} from 'lucide-react';
import ModelViewer from './model-viewer';
import {read3MF,write3MF,bounds,type MeshData,type Part} from '@/lib/three-mf';
import {useLocale} from './locale';
type Operation={action:string;mesh?:MeshData;axis?:number;cut?:number;angle?:number;size?:number[];wall?:number;shape?:string};
const printers=[{name:'A1 mini',size:180},{name:'A1',size:256},{name:'P1S',size:256},{name:'P2S',size:256},{name:'A2',size:0}];
function download(data:BlobPart,name:string,type:string){const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export default function Studio3D(){
 const {t}=useLocale();
 const [parts,setParts]=useState<Part[]>([]),[selected,select]=useState(''),[candidate,setCandidate]=useState<MeshData>(),[history,setHistory]=useState<Part[][]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[axis,setAxis]=useState(2),[percent,setPercent]=useState(50),[angle,setAngle]=useState(45),[printer,setPrinter]=useState('A1 mini'),[shape,setShape]=useState('box'),[size,setSize]=useState([80,60,35]),[wall,setWall]=useState(2),[auto,setAuto]=useState(true),[layer,setLayer]=useState('0.16');
 const worker=useRef<Worker|null>(null),requestId=useRef(0);
 useEffect(()=>()=>worker.current?.terminate(),[]);
 const active=parts.find(p=>p.id===selected),shown=candidate||active?.mesh,b=active?bounds(active.mesh):null,cut=b?b.min[axis]+b.size[axis]*percent/100:0,profile=printers.find(p=>p.name===printer)!;
 async function run(job:Operation):Promise<MeshData[]>{
  worker.current?.terminate();const w=new Worker('/3d/geometry-worker.mjs',{type:'module'});worker.current=w;const id=++requestId.current;
  return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{w.terminate();reject(Error('Tempo limite de 30 segundos. Tente uma peça mais simples.'))},30000);w.onerror=()=>{clearTimeout(timer);w.terminate();reject(Error('Falha ao carregar o motor 3D. Recarregue a página.'))};w.onmessage=({data})=>{if(data.id!==id)return;clearTimeout(timer);w.terminate();data.error?reject(Error(data.error)):resolve(data.result)};w.postMessage({...job,id})});
 }
 function commit(next:Part[]){setHistory(h=>[...h.slice(-7),parts]);setParts(next);setCandidate(undefined)}
 async function task(fn:()=>Promise<void>){setBusy(true);setMessage('');try{await fn()}catch(e){setMessage(e instanceof Error?e.message:'Não foi possível processar a peça.')}finally{setBusy(false)}}
 async function importFile(file:File){await task(async()=>{const loaded=read3MF(await file.arrayBuffer());commit(loaded);select(loaded[0].id);setPercent(50);setMessage(`${loaded.length} peça(s) importada(s). Geometria em milímetros.`);if(auto){try{const [smooth]=await run({action:'smooth',mesh:loaded[0].mesh,angle});setCandidate(smooth);setMessage('Sugestão de suavização pronta para a primeira peça. Compare as dimensões antes de aplicar.')}catch{setMessage('Arquivo importado. A suavização automática não foi possível; repare a malha no Bambu Studio ou use uma peça menor.')}}})}
 const disabled=busy||!active;
 return <div className="studio3d">
  <section className="panel studio-intro"><div><span className="badge green"><Printer size={14}/> BAMBU STUDIO</span><h2>{t('Do arquivo à peça pronta para fatiar')}</h2><p>Carregue 3MF, divida peças e prepare contornos suaves. Os arquivos são processados neste navegador. Exporte para guardar o trabalho.</p></div><label className="primary upload-button"><Upload size={17}/>{t('Carregar 3MF')}<input disabled={busy} type="file" accept=".3mf" aria-label="Carregar arquivo 3MF" onChange={e=>{const file=e.target.files?.[0];if(file)void importFile(file);e.target.value=''}}/></label></section>
  <div className="studio-grid"><div className="studio-main"><section className="panel"><div className="panel-heading"><h2>{candidate?'Prévia da suavização':'Visualização da peça'}</h2><span className="badge green">mm</span></div><ModelViewer mesh={shown} axis={axis} cut={cut} showPlane={!candidate&&!!active}/><p className="muted viewer-help">Arraste para girar · rolagem para aproximar · botão direito para mover</p></section>
  {message&&<p className="studio-message" role="status">{message}</p>}{busy&&<p role="status">Processando geometria…</p>}
  {candidate&&active&&<section className="panel studio-candidate"><h3>Compare antes de aplicar</h3><p>Original: {bounds(active.mesh).size.map(v=>v.toFixed(2)).join(' × ')} mm · Proposta: {bounds(candidate).size.map(v=>v.toFixed(2)).join(' × ')} mm</p><p>A suavização pode alterar encaixes e dimensões. Aumenta a resolução da malha; não remove linhas de camada já fatiadas.</p><div className="form-actions"><button className="secondary" disabled={busy} onClick={()=>setCandidate(undefined)}>Manter original</button><button className="primary" disabled={busy} onClick={()=>commit(parts.map(p=>p.id===active.id?{...p,mesh:candidate}:p))}>Aplicar suavização</button></div></section>}
  <section className="panel studio-parts"><div className="panel-heading"><h2>Peças do projeto ({parts.length})</h2><button className="secondary" disabled={busy||!history.length} onClick={()=>{const prev=history[history.length-1];setParts(prev);select(prev[0]?.id||'');setHistory(h=>h.slice(0,-1));setCandidate(undefined)}}><RotateCcw size={16}/>Desfazer</button></div>{parts.map(p=><button disabled={busy} key={p.id} className={'studio-part '+(p.id===selected?'selected':'')} onClick={()=>{select(p.id);setCandidate(undefined);setPercent(50)}}><Box size={20}/><span><b>{p.name}</b><small>{bounds(p.mesh).size.map(v=>v.toFixed(1)).join(' × ')} mm · {p.mesh.triangles.length/3} triângulos</small></span></button>)}{!parts.length&&<p className="muted">Comece pelo gerador ao lado ou importe um arquivo.</p>}</section></div>
  <div className="studio-controls"><section className="panel settings-card"><h3>1. Impressora e acabamento</h3><label className="field">Impressora<select value={printer} onChange={e=>setPrinter(e.target.value)}>{printers.map(p=><option key={p.name}>{p.name}</option>)}</select></label><p className="muted">{profile.size?`Volume nominal: ${profile.size} × ${profile.size} × ${profile.size} mm.`:'A2: perfil oficial não validado. Confira dimensões e perfil no Bambu Studio.'}</p>{b&&profile.size>0&&b.size.some(v=>v>profile.size)&&<p className="error">A peça excede o volume nominal. Divida ou redimensione no Bambu Studio.</p>}<label className="field">Camada sugerida · bico 0,4 mm<select value={layer} onChange={e=>setLayer(e.target.value)}><option value="0.20">0,20 mm · equilíbrio</option><option value="0.16">0,16 mm · acabamento fino</option><option value="0.12">0,12 mm · mais detalhe</option></select></label><p className="muted">Aplique o perfil correspondente no Bambu Studio e use altura de camada variável nas curvas. Revise orientação, costura e calibração do filamento.</p><label className="studio-checkbox"><input type="checkbox" checked={auto} onChange={e=>setAuto(e.target.checked)}/>Sugerir suavização ao importar</label></section>
  <section className="panel settings-card"><h3>2. Gerador paramétrico</h3><label className="field">Modelo<select value={shape} disabled={busy} onChange={e=>setShape(e.target.value)}><option value="box">Caixa organizadora aberta</option><option value="vase">Vaso cônico</option><option value="block">Bloco / base</option></select></label><div className="studio-dimensions">{(shape==='vase'?['Diâm. base','Diâm. topo','Altura']:['Largura','Profundidade','Altura']).map((name,i)=><label className="field" key={i}>{name} (mm)<input type="number" min="2" max="1000" step=".1" value={size[i]} onChange={e=>setSize(v=>v.map((n,j)=>i===j?Number(e.target.value):n))}/></label>)}</div><label className="field">Parede / fundo (mm)<input type="number" min=".5" step=".1" value={wall} onChange={e=>setWall(Number(e.target.value))}/></label><button className="primary wide" disabled={busy} onClick={()=>task(async()=>{const [mesh]=await run({action:'generate',size,wall,shape});const p={id:crypto.randomUUID(),name:shape==='box'?'Caixa organizadora':shape==='vase'?'Vaso cônico':'Bloco',mesh};commit([...parts,p]);select(p.id);setPercent(50)})}><Box size={16}/>Gerar peça</button></section>
  <section className="panel settings-card"><h3>3. Dividir e suavizar</h3><label className="field">Eixo do corte<select value={axis} disabled={disabled} onChange={e=>setAxis(Number(e.target.value))}>{['X','Y','Z'].map((a,i)=><option value={i} key={a}>{a}</option>)}</select></label><label className="field">Posição do corte: {cut.toFixed(2)} mm<input type="range" min="1" max="99" value={percent} disabled={disabled} onChange={e=>setPercent(Number(e.target.value))}/></label><button className="secondary wide" disabled={disabled} onClick={()=>task(async()=>{const result=await run({action:'split',mesh:active!.mesh,axis,cut});const newParts=result.map((mesh,i)=>({id:crypto.randomUUID(),name:active!.name+' · '+(i?'B':'A'),mesh}));commit(parts.flatMap(p=>p.id===active!.id?newParts:[p]));select(newParts[0].id);setPercent(50);setMessage('Corte concluído com faces fechadas. As partes preservam a posição de montagem; organize-as na mesa do Bambu Studio.')})}><Scissors size={16}/>Dividir peça em duas</button><label className="field">Preservar arestas acima de {angle}°<input type="range" min="15" max="90" value={angle} onChange={e=>setAngle(Number(e.target.value))}/></label><button className="secondary wide" disabled={disabled} onClick={()=>task(async()=>{const [mesh]=await run({action:'smooth',mesh:active!.mesh,angle});setCandidate(mesh)})}><Sparkles size={16}/>Prévia de suavização</button><p className="muted">Cortes exigem malhas sólidas e fechadas. Operações pesadas têm limite de 30 segundos.</p></section>
  <section className="panel settings-card"><h3>4. Abrir no Bambu Studio</h3><p>O 3MF exportado contém as geometrias em milímetros. Pintura, suportes, perfis da impressora e G-code do arquivo original não são preservados. Abra como geometria, selecione a impressora e fatie no Bambu Studio.</p><button className="primary wide" disabled={busy||!parts.length||!!candidate} onClick={()=>{try{download(write3MF(parts) as BlobPart,'fluxo-bambu.3mf','model/3mf')}catch(e){setMessage(String(e))}}}><Download size={16}/>Exportar projeto 3MF</button><button className="secondary wide" disabled={disabled||!!candidate} onClick={()=>download(write3MF([active!]) as BlobPart,'fluxo-peca.3mf','model/3mf')}>Exportar peça selecionada</button><button className="text-button" onClick={()=>download(`Fluxo — roteiro para Bambu Studio\nImpressora: ${printer}\nBico de referência: 0,4 mm\nAltura de camada sugerida: ${layer} mm\n\n1. Importe o 3MF como geometria.\n2. Selecione o perfil oficial da sua impressora e filamento.\n3. Organize e oriente as partes na mesa.\n4. Teste altura de camada variável nas curvas.\n5. Confira costura, suportes, encaixes e primeira camada.\n6. Revise a prévia de fatiamento antes de imprimir.\n\nEste roteiro não é um preset importável nem G-code.`, 'fluxo-bambu-acabamento.txt','text/plain')}>Baixar roteiro de acabamento</button></section></div></div>
 </div>;
}
