"use client";
import {useState,useEffect} from 'react';
import dynamic from 'next/dynamic';
const Studio3D=dynamic(()=>import('@/components/erp/studio3d'),{ssr:false,loading:()=> <p>Carregando estúdio 3D…</p>});
import {createClient} from '@supabase/supabase-js';
import {Dialog} from 'radix-ui';
import {AreaChart,Area,ResponsiveContainer,CartesianGrid,XAxis,YAxis,Tooltip} from 'recharts';
import {Workflow,LayoutDashboard,Wallet,Box,Calculator,ShoppingBag,Settings,ArrowRight,ArrowUpRight,ArrowDownLeft,Plus,Search,X,Check,Printer,Menu,Download,Pencil,Trash2,RotateCcw,Package,Building2,SlidersHorizontal,Globe,Mail} from 'lucide-react';
import {LocaleProvider,useLocale,RegionalControls} from '@/components/erp/locale';
import {BusinessForm,ProductForm,EntryForm,StockForm,Photo,Field,Select} from '@/components/erp/forms';
import Pricing from '@/components/erp/pricing';
import Marketplace from '@/components/erp/marketplace';
import {models,itemLabels,dateRange,financialSeries,defaultBusinesses,type ModelId,type RangeMode} from '@/lib/erp';
import {roundCurrency} from '@/lib/currency';
const demoUnits=defaultBusinesses.map((b,i)=>({id:'business-'+i,name:b.name,model:b.model,description:'',contact_email:'',phone:'',deleted_at:null}));
const productNames=[['Vaso espiral','Suporte articulado','Filamento PLA Preto','Bico de impressora'],['Troca de óleo','Revisão preventiva','Óleo lubrificante','Pastilha de freio'],['Pneu aro 15','Balanceamento','Borracha para reparo','Válvula de pneu'],['Marmita artesanal','Bolo caseiro','Farinha de trigo','Forma de silicone'],['Diária Studio','Limpeza de estadia','Produto de limpeza','Fechadura']];
const demoProducts=demoUnits.flatMap((b,i)=>productNames[i].map((name,j)=>({id:`p-${i}-${j}`,business_id:b.id,name,category:b.name,item_type:j===2?'material':j===3?'part':i===4||i===1&&j<2?'service':'finished',unit:j===2?'kg':'un',cost:[18.5,32,90,12][j],price:[59.9,89.9,120,29.9][j],stock:[24,12,2.5,0][j],min_stock:[5,3,3,2][j],currency:'BRL',sku:`SKU-${i+1}${j+1}`,supplier:'',location:'A1',description:'',deleted_at:null})));
const demoEntries=demoUnits.flatMap((b,j)=>Array.from({length:30},(_,i)=>({id:`e-${j}-${i}`,business_id:b.id,description:i%3?productNames[j][0]:'Insumos e operação',type:i%3?'income':'expense',amount:i%3?490+i*37:380+i*15,date:`2026-${String(i<16?9:8).padStart(2,'0')}-${String(i<16?i%13+1:i%28+1).padStart(2,'0')}`,category:i%3?'Vendas':'Operação',status:i%8?'paid':'pending',product_id:i%3?`p-${j}-0`:null,quantity:i%3?10:null,currency:'BRL',contact:'',payment_method:'transfer',notes:'',deleted_at:null})));
const navigation=[['Visão geral',LayoutDashboard],['Meus negócios',Building2],['Fluxo da empresa',Workflow],['Financeiro',Wallet],['Produtos e serviços',Box],['Estoque',Package],['Precificação',Calculator],['Marketplace',ShoppingBag],['Estúdio 3D',Printer]] as const;
type Modal={kind:string;row?:any;table?:string}|null;
async function allRows(db:any,table:string){let rows:any[]=[];for(let from=0;;from+=1000){const r=await db.from(table).select('*').order('created_at',{ascending:false}).order('id').range(from,from+999);if(r.error)throw r.error;rows.push(...r.data);if(r.data.length<1000)return rows}}
export default function Page(){return <LocaleProvider><Workspace/></LocaleProvider>}
function Workspace(){
const {t,money,currency,lang}=useLocale();
const [tab,T]=useState('Visão geral'),[units,U]=useState<any[]>(demoUnits),[selected,SEL]=useState('business-0'),[products,P]=useState<any[]>(demoProducts),[entries,E]=useState<any[]>(demoEntries),[moves,MOV]=useState<any[]>([]),[demo,D]=useState(true),[modal,M]=useState<Modal>(null),[msg,MSG]=useState(''),[busy,B]=useState(false),[query,Q]=useState(''),[filter,F]=useState('all'),[stockFilter,SF]=useState('all'),[trash,TRASH]=useState(false),[client,C]=useState<any>(null),[session,S]=useState<any>(null),[menu,MENU]=useState(false),[signup,SU]=useState(false),[config,CFG]=useState<any>({}),[mode,MODE]=useState<RangeMode>('month'),[anchor,A]=useState('2026-09-13'),[start,START]=useState('2026-09-01'),[end,END]=useState('2026-09-30');
useEffect(()=>{if(!msg)return;const timer=setTimeout(()=>MSG(''),7000);return()=>clearTimeout(timer)},[msg]);
useEffect(()=>{let subscription:any,active=true;fetch('/api/config').then(r=>r.json()).then(async (c:any)=>{if(!active)return;CFG(c);if(!c.url||!c.key)return;const db=createClient(c.url,c.key,{auth:{flowType:'pkce',detectSessionInUrl:true}});C(db);subscription=db.auth.onAuthStateChange((_e:any,s:any)=>{if(active)S(s)}).data.subscription;const {data}=await db.auth.getSession();if(active)S(data.session)}).catch(()=>MSG(t('Falha de conexão. Tente novamente.')));return()=>{active=false;subscription?.unsubscribe()}},[]);
useEffect(()=>{if(!client||!session?.user?.id)return;let active=true;(async()=>{B(true);try{const [u,p,e,m]=await Promise.all(['business_units','products','entries','stock_movements'].map(table=>allRows(client,table)));if(!active)return;U(u);P(p);E(e);MOV(m);SEL(u.find(x=>!x.deleted_at)?.id||'');D(false);A(new Date().toLocaleDateString('en-CA'));}catch{if(active)MSG(t('Falha de conexão. Tente novamente.'))}finally{if(active)B(false)}})();return()=>{active=false}},[client,session?.user?.id]);
const business=units.find(b=>b.id===selected&&!b.deleted_at),bp=products.filter(p=>p.business_id===selected),be=entries.filter(e=>e.business_id===selected),catalog=bp.filter(p=>p.currency===currency),range=dateRange(mode,anchor,start,end),visible=be.filter(e=>e.currency===currency&&range&&e.date>=range.start&&e.date<=range.end),activeEntries=visible.filter(e=>!e.deleted_at),paid=activeEntries.filter(e=>e.status==='paid'),sum=(type:string)=>paid.filter(e=>e.type===type).reduce((a,e)=>a+Number(e.amount),0),income=sum('income'),expense=sum('expense'),sales=paid.filter(e=>e.type==='income'&&e.product_id&&e.quantity),quantity=sales.reduce((a,e)=>a+Number(e.quantity),0),avg=quantity?sales.reduce((a,e)=>a+Number(e.amount),0)/quantity:0,stock=catalog.filter(p=>p.item_type!=='service'&&!p.deleted_at),low=stock.filter(p=>Number(p.stock)<=Number(p.min_stock));
const chart=financialSeries(activeEntries,range);
function go(name:string){T(name);Q('');F('all');SF('all');TRASH(false);MENU(false)}
function open(kind:string,row?:any,table?:string){M({kind,row,table})}
function selectBusiness(id:string){SEL(id);Q('');F('all');TRASH(false);MENU(false)}
const updateLocal=(table:string,record:any)=>{const setter=table==='products'?P:table==='entries'?E:U;setter((rows:any[])=>rows.some(x=>x.id===record.id)?rows.map(x=>x.id===record.id?record:x):[record,...rows])};
async function persist(table:string,data:any,row?:any){const record={...data,...(!row?{id:crypto.randomUUID(),created_at:new Date().toISOString(),deleted_at:null}:{})};if(demo){const saved={...row,...record};updateLocal(table,saved);return saved}let result;const payload={...record,owner_id:session.user.id};if(row)result=await client.from(table).update(payload).eq('id',row.id).select().single();else result=await client.from(table).insert(payload).select().single();if(result.error)throw result.error;updateLocal(table,result.data);return result.data}
async function saveBusiness(data:any){B(true);try{const saved=await persist('business_units',data,modal?.row);SEL(saved.id);M(null);MSG(t('Registro salvo.'))}catch{MSG(t('Não foi possível salvar. Os campos foram preservados.'))}finally{B(false)}}
async function saveProduct(data:any,file:File|null,remove:boolean){if(!business)return;B(true);let uploaded='';try{const row=modal?.row;let photo=row?.image_path||null,preview=row?.image_preview||'';if(remove){photo=null;preview=''}if(file){if(demo){preview=URL.createObjectURL(file)}else{const ext={'image/png':'png','image/jpeg':'jpg','image/webp':'webp'}[file.type as 'image/png'];uploaded=session.user.id+'/'+crypto.randomUUID()+'.'+ext;const r=await client.storage.from('product-photos').upload(uploaded,file,{contentType:file.type,upsert:false});if(r.error)throw r.error;photo=uploaded}}await persist('products',{...data,business_id:business.id,category:business.name,image_path:photo,...(demo?{image_preview:preview}:{})},row);if(!demo&&row?.image_path&&row.image_path!==photo){await client.storage.from('product-photos').remove([row.image_path]).catch(()=>{})}if(demo&&row?.image_preview&&row.image_preview!==preview)URL.revokeObjectURL(row.image_preview);M(null);MSG(t('Registro salvo.'))}catch{if(uploaded)await client.storage.from('product-photos').remove([uploaded]);MSG(t('Não foi possível salvar. Os campos foram preservados.'))}finally{B(false)}}
async function saveEntry(data:any){if(!business)return;B(true);try{await persist('entries',{...data,business_id:business.id},modal?.row);M(null);MSG(t('Registro salvo.'))}catch{MSG(t('Não foi possível salvar. Os campos foram preservados.'))}finally{B(false)}}
async function archive(table:string,row:any,restore=false){B(true);try{await persist(table,{deleted_at:restore?null:new Date().toISOString()},row);if(table==='business_units'&&row.id===selected&&!restore)SEL(units.find(x=>x.id!==row.id&&!x.deleted_at)?.id||'');M(null);MSG(t(restore?'Registro restaurado.':'Registro movido para a lixeira.'))}catch{MSG(t('Falha de conexão. Tente novamente.'))}finally{B(false)}}
async function moveStock(delta:number,note:string){const p=modal?.row;if(!p)return;if(!Number.isFinite(delta)||delta===0||Number(p.stock)+delta<0){MSG(t('Saldo insuficiente ou item indisponível.'));return}B(true);try{if(demo){const balance=Math.round((Number(p.stock)+delta)*1000)/1000;updateLocal('products',{...p,stock:balance});MOV(m=>[{id:crypto.randomUUID(),product_id:p.id,delta,balance,note,created_at:new Date().toISOString()},...m])}else{const r=await client.rpc('adjust_stock',{p_product:p.id,p_delta:delta,p_note:note});if(r.error)throw r.error;updateLocal('products',r.data);const m=await allRows(client,'stock_movements');MOV(m)}M(null);MSG(t('Movimentação registrada.'))}catch{MSG(t('Saldo insuficiente ou item indisponível.'))}finally{B(false)}}
async function applyPrice(id:string,cost:number,price:number){const p=catalog.find(p=>p.id===id&&!p.deleted_at);if(!p)return;B(true);try{await persist('products',{cost:roundCurrency(cost,p.currency),price:roundCurrency(price,p.currency)},p);MSG(t('Registro salvo.'))}catch{MSG(t('Falha de conexão. Tente novamente.'))}finally{B(false)}}
async function authenticate(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!client)return;B(true);const f=new FormData(e.currentTarget),credentials={email:String(f.get('email')),password:String(f.get('password'))};try{const r=signup?await client.auth.signUp({...credentials,options:{emailRedirectTo:window.location.origin+'/'}}):await client.auth.signInWithPassword(credentials);if(r.error)throw r.error;M(null);MSG(t(r.data.session?'Conta conectada.':'Confira seu e-mail para confirmar o cadastro.'))}catch(error:any){MSG(error?.message||t('Falha de conexão. Tente novamente.'))}finally{B(false)}}
async function google(){if(!client||!config.google)return;const {error}=await client.auth.signInWithOAuth({provider:'google',options:{redirectTo:window.location.origin+'/'}});if(error)MSG(error.message)}
async function logout(){if(client){const {error}=await client.auth.signOut();if(error){MSG(t('Falha de conexão. Tente novamente.'));return}}S(null);D(true);U(demoUnits);P(demoProducts);E(demoEntries);MOV([]);SEL('business-0')}
function exportCSV(){const rows=[[t('Descrição'),t('Tipo'),t('Valor'),t('Moeda'),t('Data'),t('Categoria'),t('Status')],...activeEntries.map(e=>[e.description,t(e.type==='income'?'Receita':'Despesa'),e.amount,e.currency,e.date,e.category,t(e.status==='paid'?'Realizado':'Pendente')])];const csv='\uFEFF'+rows.map(r=>r.map(v=>'"'+String(v).replace(/^[=+@-]/,"'").replaceAll('"','""')+'"').join(';')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'}));a.download=`fluxo-${currency}-${range?.start||'export'}.csv`;a.click();URL.revokeObjectURL(a.href)}
const actions=(table:string,row:any)=><div className="row-actions">{row.deleted_at?<button className="secondary" disabled={busy} onClick={()=>archive(table,row,true)}><RotateCcw size={15}/>{t('Restaurar')}</button>:<><button aria-label={t('Editar')+' '+(row.name||row.description)} title={t('Editar')} onClick={()=>open(table==='products'?'product':table==='entries'?'entry':'business',row)}><Pencil size={16}/></button><button aria-label={t('Excluir')+' '+(row.name||row.description)} title={t('Excluir')} onClick={()=>open('delete',row,table)}><Trash2 size={16}/></button></>}</div>;
const searchBar=<label className="search"><Search size={17}/><input aria-label={t('Buscar')} placeholder={t('Buscar')} value={query} onChange={e=>Q(e.target.value)}/></label>;
const trashToggle=<div className="tabs">{[false,true].map(v=><button className={trash===v?'selected':''} onClick={()=>TRASH(v)} key={String(v)}>{t(v?'Lixeira':'Ativos')}</button>)}</div>;
const filters=<section className="period-panel panel"><div className="period-buttons">{[['day','Dia'],['week','Semana'],['month','Mês'],['year','Ano'],['custom','Período']].map(([v,l])=><button key={v} className={mode===v?'selected':''} onClick={()=>MODE(v as RangeMode)}>{t(l)}</button>)}</div><div className="period-fields">{mode==='custom'?<><Field label="De" type="date" value={start} onChange={(e:any)=>START(e.target.value)}/><Field label="Até" type="date" value={end} onChange={(e:any)=>END(e.target.value)}/></>:<Field label="Data de referência" type="date" value={anchor} onChange={(e:any)=>A(e.target.value)}/>}<span>{range?range.start.split('-').reverse().join('/')+' — '+range.end.split('-').reverse().join('/'):t('Período inválido. Selecione até 10 anos.')}</span></div></section>;
const graph=<section className="panel finance-chart"><div className="panel-heading"><div><h2>{t('Movimentação financeira')}</h2><p>{t('Somente lançamentos realizados entram no gráfico e no resultado de caixa.')}</p></div><div className="legend"><span><i/>{t('Receitas')}</span><span><i/>{t('Despesas')}</span></div></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart} margin={{top:15,right:15,left:0,bottom:0}}><defs><linearGradient id="income" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#239776" stopOpacity={.22}/><stop offset="100%" stopColor="#239776" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} strokeDasharray="3 5" stroke="#e8eeea"/><XAxis dataKey="day" axisLine={false} tickLine={false} minTickGap={25} tick={{fontSize:12,fill:'#6c8273'}}/><YAxis axisLine={false} tickLine={false} tickFormatter={n=>new Intl.NumberFormat(lang,{notation:'compact'}).format(n)} tick={{fontSize:12,fill:'#6c8273'}}/><Tooltip formatter={(v:any)=>money(Number(v))}/><Area name={t('Receitas')} type="monotone" dataKey="Receitas" stroke="#269879" strokeWidth={2.5} fill="url(#income)"/><Area name={t('Despesas')} type="monotone" dataKey="Despesas" stroke="#d6a253" strokeWidth={2} fill="transparent"/></AreaChart></ResponsiveContainer></div></section>;
const stats=<div className="stats-grid">{[['Receitas',income,ArrowUpRight],['Despesas',expense,ArrowDownLeft],['Resultado de caixa',income-expense,Wallet],['Venda média por unidade',avg,ShoppingBag]].map(([l,v,Icon]:any,i)=><section className={'stat '+(i===2?'featured':'')} key={l}><div className="stat-head"><span>{t(l)}</span><Icon size={19}/></div><strong>{money(v)}</strong><p className="stat-sub">{t(['Recebimentos realizados no período.','Pagamentos realizados no período.','Receitas menos despesas realizadas.','Vendas vinculadas a produtos e quantidades.'][i])}</p></section>)}</div>;
const descriptors:Record<string,string>={'Estúdio 3D':'Prepare suas peças para o Bambu Studio: gere, divida, suavize e exporte em 3MF.','Visão geral':'Acompanhe o caixa, seus produtos e as próximas decisões.','Meus negócios':'Escolha um negócio para acessar seus dados. Você pode editar o nome, trocar o modelo e restaurar negócios excluídos.','Produtos e serviços':'Cadastre fotos, custos, fornecedores e detalhes. O estoque é gerenciado por movimentações.','Financeiro':'Somente lançamentos realizados entram no gráfico e no resultado de caixa.','Estoque':'Veja produtos prontos, matérias-primas e peças. Filtre por tipo ou nível de estoque.','Precificação':'Ajuste os parâmetros da operação e veja a composição do preço em tempo real.','Marketplace':'Descreva produto, marca, cor e tamanho para encontrar ofertas mais próximas.','Configurações':'Dados e descrições cadastrados não são traduzidos.','Fluxo da empresa':'Acompanhe o caixa, seus produtos e as próximas decisões.'};
return <div><aside className={'sidebar '+(menu?'mobile-open':'')}><button className="logo" onClick={()=>go('Visão geral')}><span><Workflow size={24}/></span>fluxo<span className="logo-dot">.</span></button><div className="company"><span className="company-avatar"><Building2 size={21}/></span><div><b>{t('Meu negócio')}</b><small>{business?.name||t('Selecionar')}</small></div><select aria-label={t('Meu negócio')} value={selected} onChange={e=>e.target.value==='add'?open('business'):selectBusiness(e.target.value)}><option value="" disabled>{t('Selecionar')}</option>{units.filter(u=>!u.deleted_at).map(b=><option key={b.id} value={b.id}>{b.name}</option>)}<option value="add">＋ {t('Adicionar negócio')}</option></select></div><nav>{navigation.map(([name,Icon])=><button className={tab===name?'active':''} onClick={()=>go(name)} key={name}><Icon size={19}/>{t(name)}</button>)}</nav><div className="sidebar-bottom"><button className="settings-link" onClick={()=>go('Configurações')}><Settings size={19}/>{t('Configurações')}</button><button className="user" onClick={()=>open('auth')}><span className="avatar">{session?'ME':'D'}</span><span><b>{t(session?'Minha conta':'Demonstração interativa')}</b><small>{session?.user?.email||'Fluxo ERP'}</small></span></button></div></aside><div className="workspace"><header className="topbar"><button className="mobile-toggle" aria-label="Menu" onClick={()=>MENU(!menu)}><Menu/></button><span className="breadcrumb">{business?.name||t('Meu negócio')} <span>/</span><b>{t(tab)}</b></span><div className="top-actions"><RegionalControls compact/>{session?<button className="text-button" onClick={logout}>{t('Sair')}</button>:<button className="text-button" onClick={()=>open('auth')}>{t('Entrar')}<ArrowUpRight size={16}/></button>}</div></header><main><div className="page-heading"><div><p className="eyebrow">FLUXO ERP · {currency}</p><h1>{t(tab==='Visão geral'?'Seu negócio, por inteiro.':tab)}</h1><p>{t(descriptors[tab])}</p></div><div className="heading-actions">{tab==='Meus negócios'?<button className="primary" disabled={busy} onClick={()=>open('business')}><Plus size={18}/>{t('Adicionar negócio')}</button>:['Produtos e serviços','Estoque'].includes(tab)?<button className="primary" disabled={!business||busy} onClick={()=>open('product')}><Plus size={18}/>{t('Adicionar item')}</button>:['Visão geral','Financeiro'].includes(tab)?<button className="primary" disabled={!business||busy} onClick={()=>open('entry')}><Plus size={18}/>{t('Novo lançamento')}</button>:null}</div></div>{demo&&<div className="demo-note"><span>{t('Explore à vontade. Os exemplos são reiniciados ao recarregar.')}</span><button onClick={()=>open('auth')}>{t('Usar meus dados')}<ArrowRight size={15}/></button></div>}{busy&&<p role="status" className="loading-line">{t('Conectando sua empresa…')}</p>}
{!business&&!['Meus negócios','Configurações','Marketplace','Estúdio 3D'].includes(tab)?<section className="panel empty"><Building2 size={38}/><h2>{t('Crie um negócio para começar.')}</h2><button className="primary" onClick={()=>open('business')}>{t('Adicionar negócio')}</button></section>:<>
{['Visão geral','Financeiro'].includes(tab)&&<>{filters}{stats}{graph}<div className="pending-totals"><span>{t('A receber')}: <b>{money(activeEntries.filter(e=>e.type==='income'&&e.status==='pending').reduce((a,e)=>a+Number(e.amount),0))}</b></span><span>{t('A pagar')}: <b>{money(activeEntries.filter(e=>e.type==='expense'&&e.status==='pending').reduce((a,e)=>a+Number(e.amount),0))}</b></span><small>{currency} · {range?.start} / {range?.end}</small></div>{tab==='Financeiro'?<section className="panel"><div className="panel-heading">{trashToggle}<div className="tabs">{[['all','Todos'],['income','Receitas'],['expense','Despesas']].map(([v,l])=><button className={filter===v?'selected':''} onClick={()=>F(v)} key={v}>{t(l)}</button>)}</div><button className="secondary" onClick={exportCSV}><Download size={16}/>{t('Exportar CSV')}</button></div><div className="table-scroll"><table><thead><tr>{['Lançamento','Cliente / fornecedor','Data','Status','Valor','Ações'].map(l=><th key={l}>{t(l)}</th>)}</tr></thead><tbody>{visible.filter(e=>!!e.deleted_at===trash&&(filter==='all'||e.type===filter)).map(e=><tr key={e.id}><td><span className={'entry-icon '+e.type}>{e.type==='income'?<ArrowUpRight size={17}/>:<ArrowDownLeft size={17}/>}</span><span><b>{e.description}</b><small>{e.category}</small></span></td><td>{e.contact||'—'}</td><td>{new Date(e.date+'T12:00:00').toLocaleDateString(lang)}</td><td><span className={'badge '+(e.status==='paid'?'green':'orange')}>{t(e.status==='paid'?'Realizado':'Pendente')}</span></td><td>{e.type==='income'?'+':'−'} {money(e.amount,e.currency)}</td><td>{actions('entries',e)}</td></tr>)}</tbody></table>{!visible.filter(e=>!!e.deleted_at===trash&&(filter==='all'||e.type===filter)).length&&<p className="empty">{t('Nenhum registro encontrado.')}</p>}</div></section>:<div className="overview-bottom"><section className="panel settings-card"><h2>{t('Estoque')}</h2><p>{t('Itens para repor')}: <b>{low.length}</b></p>{low.slice(0,3).map(p=><div className="compact-product" key={p.id}><Photo product={p} db={client}/><span>{p.name}<small>{Number(p.stock)} {p.unit} · {t('Mínimo')} {Number(p.min_stock)}</small></span><button onClick={()=>{go('Estoque');open('stock',p)}}><ArrowRight size={17}/></button></div>)}<button className="text-button" onClick={()=>go('Estoque')}>{t('Abrir módulo')}<ArrowRight size={17}/></button></section><section className="pricing-callout"><span className="callout-icon"><Calculator size={24}/></span><h2>{t('Seu preço, com todos os custos.')}</h2><p>{t('Calcule materiais, tempo e despesas com o modelo do seu negócio.')}</p><button onClick={()=>go('Precificação')}>{t('Precificação')}<ArrowUpRight size={18}/></button></section></div>}</>}
{tab==='Meus negócios'&&<><div className="toolbar">{trashToggle}{searchBar}</div><div className="business-grid">{units.filter(b=>!!b.deleted_at===trash&&b.name.toLowerCase().includes(query.toLowerCase())).map(b=><section className={'panel business-card '+(b.id===selected?'current':'')} key={b.id}><div className="workflow-top"><span className="step-icon"><Building2/></span>{actions('business_units',b)}</div><h2>{b.name}</h2><span className="badge green">{t(models.find(m=>m.id===b.model)?.title||'Serviços e projetos')}</span><p>{b.description||t(models.find(m=>m.id===b.model)?.description||'')}</p>{b.contact_email&&<small>{b.contact_email}</small>}{b.phone&&<small>{b.phone}</small>}{!b.deleted_at&&<button className="secondary wide" onClick={()=>{selectBusiness(b.id);go('Visão geral')}}>{t('Selecionar')}<ArrowRight size={17}/></button>}</section>)}</div></>}
{tab==='Produtos e serviços'&&<><div className="toolbar">{trashToggle}{searchBar}</div><div className="product-grid">{catalog.filter(p=>!!p.deleted_at===trash&&p.name.toLowerCase().includes(query.toLowerCase())).map(p=><article className="panel catalog-card" key={p.id}><Photo product={p} db={client} large/><div className="catalog-body"><div className="catalog-top"><span className="badge green">{t(itemLabels[p.item_type])}</span>{actions('products',p)}</div><h2>{p.name}</h2><small>{p.sku||'—'} · {p.unit}</small><p>{p.description||'—'}</p><div className="catalog-price"><span>{t('Preço de venda')}<b>{money(p.price,p.currency)}</b></span><span>{t('Custo unitário')}<b>{money(p.cost,p.currency)}</b></span></div><div className="catalog-footer"><span>{t('Margem bruta')}: {Number(p.price)?((p.price-p.cost)/p.price*100).toLocaleString(lang,{maximumFractionDigits:1}):0}%</span><span>{Number(p.stock)} {p.unit}</span></div></div></article>)}</div>{!catalog.filter(p=>!!p.deleted_at===trash&&p.name.toLowerCase().includes(query.toLowerCase())).length&&<p className="empty panel">{t('Nenhum registro encontrado.')}</p>}</>}
{tab==='Estoque'&&<><div className="stats-grid stock-stats">{[[t('Itens cadastrados'),stock.length],[t('Itens para repor'),low.length],[t('Valor em estoque'),money(stock.reduce((a,p)=>a+Number(p.cost)*Number(p.stock),0))]].map(([l,v])=><section className="stat" key={l}><span className="stat-head">{l}</span><strong>{v}</strong></section>)}</div><section className="panel"><div className="panel-heading">{searchBar}<select aria-label={t('Tipo')} value={filter} onChange={e=>F(e.target.value)}><option value="all">{t('Todos os tipos')}</option>{Object.entries(itemLabels).filter(([k])=>k!=='service').map(([v,l])=><option value={v} key={v}>{t(l)}</option>)}</select><select aria-label={t('Status')} value={stockFilter} onChange={e=>SF(e.target.value)}><option value="all">{t('Todos os saldos')}</option><option value="ready">{t('Disponível')}</option><option value="low">{t('Estoque baixo')}</option><option value="zero">{t('Sem estoque')}</option></select></div><div className="table-scroll"><table><thead><tr>{['Produto / serviço','Tipo','Localização','Saldo atual','Estoque mínimo','Status','Ações'].map(l=><th key={l}>{t(l)}</th>)}</tr></thead><tbody>{stock.filter(p=>(filter==='all'||p.item_type===filter)&&p.name.toLowerCase().includes(query.toLowerCase())&&(stockFilter==='all'||stockFilter==='ready'&&p.stock>0||stockFilter==='low'&&p.stock<=p.min_stock||stockFilter==='zero'&&Number(p.stock)===0)).map(p=><tr key={p.id}><td><Photo product={p} db={client}/><span><b>{p.name}</b><small>{p.sku||'—'}</small></span></td><td>{t(itemLabels[p.item_type])}</td><td>{p.location||'—'}</td><td><b>{Number(p.stock)} {p.unit}</b></td><td>{Number(p.min_stock)} {p.unit}</td><td><span className={'badge '+(p.stock<=p.min_stock?'orange':'green')}>{t(Number(p.stock)===0?'Sem estoque':p.stock<=p.min_stock?'Estoque baixo':'Disponível')}</span></td><td><div className="stock-actions"><button className="secondary" onClick={()=>open('stock',p)}>{t('Movimentar')}</button>{actions('products',p)}</div></td></tr>)}</tbody></table></div></section><section className="panel movement-panel"><div className="panel-heading"><h2>{t('Histórico de movimentações')}</h2></div><div className="table-scroll"><table><thead><tr>{['Data','Produto / serviço','Quantidade','Saldo após movimento','Motivo'].map(l=><th key={l}>{t(l)}</th>)}</tr></thead><tbody>{moves.filter(m=>bp.some(p=>p.id===m.product_id&&p.currency===currency)).map(m=>{const p=bp.find(p=>p.id===m.product_id);return <tr key={m.id}><td>{new Date(m.created_at).toLocaleString(lang)}</td><td>{p?.name}</td><td>{m.delta>0?'+':''}{Number(m.delta)} {p?.unit}</td><td>{Number(m.balance)} {p?.unit}</td><td>{m.note}</td></tr>})}</tbody></table>{!moves.some(m=>bp.some(p=>p.id===m.product_id&&p.currency===currency))&&<p className="empty">{t('Nenhum registro encontrado.')}</p>}</div></section></>}
{tab==='Precificação'&&<Pricing key={selected+'-'+currency} model={business?.model||'service'} products={bp} onApply={applyPrice} busy={busy}/>}
{tab==='Estúdio 3D'&&<Studio3D/>}
{tab==='Marketplace'&&<Marketplace session={session} configured={!!config.marketplace}/>}
{tab==='Fluxo da empresa'&&<div className="workflow-grid">{[['Preparar','Cadastre produtos e insumos, com fotos, códigos e fornecedores.','Produtos e serviços',Box],['Precificar','Calcule materiais, tempo e despesas com o modelo do seu negócio.','Precificação',Calculator],['Vender','Registre recebimentos e pagamentos e acompanhe as pendências.','Financeiro',Wallet],['Acompanhar','Confira o saldo, o estoque disponível e o que precisa repor.','Estoque',Package]].map(([l,desc,target,Icon]:any,i)=><section className="panel workflow-card" key={l}><div className="workflow-top"><span className="step-icon"><Icon/></span><span>0{i+1}</span></div><h2>{t(l)}</h2><p>{t(desc)}</p><button className="secondary" onClick={()=>go(target)}>{t('Abrir módulo')}<ArrowRight size={17}/></button></section>)}</div>}
{tab==='Configurações'&&<div className="settings-grid"><section className="panel settings-card"><h2>{t('Preferências regionais')}</h2><RegionalControls/><p>{t('Moeda dos novos registros e filtro dos totais. Valores existentes mantêm a moeda original. Não há conversão automática.')}</p><p>{t('Moedas ISO 4217 disponíveis no navegador.')}</p><p>{t('Dados e descrições cadastrados não são traduzidos.')}</p></section><section className="panel settings-card"><h2>{t('Conexões')}</h2>{[['Supabase',!!client],['Google',!!config.google],['Google Shopping',!!config.marketplace],['Resend',false]].map(([l,ok])=><div className="connection" key={String(l)}><Globe size={20}/><div><b>{l}</b></div><span className={'badge '+(ok?'green':'orange')}>{t(ok?'Disponível':'Falta configurar')}</span></div>)}<p>{t('Resend pausado para configuração posterior.')}</p><p>{t('Login Google aguardando configuração.')}</p></section></div>}
</>}<footer><span><Workflow size={15}/>fluxo · {t('Clareza para seguir em frente.')}</span><span>{currency} · {demo?t('Demonstração interativa'):t('Minha conta')}</span></footer></main></div>
<Dialog.Root open={!!modal} onOpenChange={o=>!o&&!busy&&M(null)}><Dialog.Portal><Dialog.Overlay className="modal-overlay"/><Dialog.Content className={'modal '+(['business','product','entry'].includes(modal?.kind||'')?'modal-wide':'')}><Dialog.Title>{t(modal?.kind==='delete'?'Excluir este registro?':modal?.kind==='auth'?'Sua conta, seu espaço.':modal?.kind==='stock'?'Movimentar':modal?.row?'Editar':modal?.kind==='business'?'Novo negócio':modal?.kind==='product'?'Novo item':'Novo lançamento')}</Dialog.Title><Dialog.Description>{t(modal?.kind==='delete'?(modal.table==='business_units'?'Ao excluir um negócio, seus registros ficam preservados e voltam ao restaurá-lo.':'O registro irá para a lixeira e poderá ser restaurado. O histórico será preservado.'):modal?.kind==='auth'?'Entre ou crie uma conta para salvar seus negócios e trabalhar em outros dispositivos.':demo?'Você está editando exemplos temporários.':'As informações serão salvas na sua conta.')}</Dialog.Description><Dialog.Close className="modal-close" disabled={busy} aria-label={t('Fechar')}><X size={20}/></Dialog.Close>{modal?.kind==='business'&&<BusinessForm row={modal.row} busy={busy} onSave={saveBusiness}/>} {modal?.kind==='product'&&<ProductForm row={modal.row} busy={busy} onSave={saveProduct} db={client}/>} {modal?.kind==='entry'&&<EntryForm row={modal.row} busy={busy} onSave={saveEntry} products={bp}/>} {modal?.kind==='stock'&&<StockForm product={modal.row} busy={busy} onSave={moveStock}/>} {modal?.kind==='delete'&&<><h3>{modal.row.name||modal.row.description}</h3><div className="form-actions"><button className="secondary" disabled={busy} onClick={()=>M(null)}>{t('Cancelar')}</button><button className="danger" disabled={busy} onClick={()=>archive(modal.table!,modal.row)}><Trash2 size={17}/>{t('Excluir')}</button></div></>} {modal?.kind==='auth'&&<><button className="google-button" disabled={!config.google||busy} onClick={google}><span>G</span>{t('Continuar com Google')}</button>{!config.google&&<p className="muted">{t('Login Google aguardando configuração.')}</p>}<form onSubmit={authenticate}><Field label="E-mail" name="email" type="email" required autoComplete="email"/><Field label="Senha" name="password" type="password" required minLength={8} autoComplete={signup?'new-password':'current-password'}/><div className="form-actions"><button className="secondary" type="button" onClick={()=>SU(!signup)}>{t(signup?'Já tenho conta':'Quero criar conta')}</button><button className="primary" disabled={!client||busy}>{t(signup?'Criar conta':'Entrar')}<ArrowRight size={17}/></button></div></form></>}</Dialog.Content></Dialog.Portal></Dialog.Root>{msg&&<div className="toast" role="status"><Check size={18}/>{msg}<button aria-label={t('Fechar')} onClick={()=>MSG('')}><X size={16}/></button></div>}</div>
}
