export const money=(n:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n);
export type ModelId='printing'|'mechanic'|'food'|'lodging'|'retail'|'service';
export const models:{id:ModelId;title:string;keywords:string[];description:string;examples:string[]}[]=[
{id:'printing',title:'Impressão 3D',keywords:['3d','impress','filamento','resina'],description:'Material por peso, horas de máquina, energia, manutenção e acabamento.',examples:['Peça em PLA','Peça em resina','Filamento PLA (kg)']},
{id:'mechanic',title:'Mecânica e manutenção',keywords:['mecan','pneu','oficina','auto','reparo','manutenc'],description:'Peças, horas de serviço, mão de obra e custos fixos por hora produtiva.',examples:['Troca de óleo','Revisão','Peça de reposição']},
{id:'food',title:'Cozinha e produção',keywords:['cozinha','comida','bolo','confeit','padaria','restaurante','marmita'],description:'Ingredientes, perdas, embalagem e rendimento por lote.',examples:['Marmita','Bolo artesanal','Ingredientes (kg)']},
{id:'lodging',title:'Hospedagem',keywords:['airbnb','hosped','hotel','pousada','aluguel','imovel'],description:'Limpeza por estadia, noites ocupadas, custos mensais e taxas.',examples:['Diária','Limpeza por estadia','Enxoval']},
{id:'retail',title:'Comércio e revenda',keywords:['loja','venda','roupa','moda','eletron','papelaria','comerc'],description:'Compra, frete, embalagem e despesas rateadas por unidade.',examples:['Produto para revenda','Embalagem','Acessório']},
{id:'service',title:'Serviços e projetos',keywords:['servico','design','consult','beleza','salao','marcen','artesan','projeto'],description:'Materiais, horas de trabalho e custos fixos por hora.',examples:['Serviço por hora','Projeto personalizado','Material de consumo']}
];
export const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
export function recommendModels(name:string){const n=normalize(name);return [...models].map(m=>({...m,score:m.keywords.reduce((a,k)=>a+(n.includes(k)?1:0),0)})).sort((a,b)=>b.score-a.score)}
export type BusinessOption={name:string;model:ModelId};
export const defaultBusinesses:BusinessOption[]=[{name:'Impressão 3D',model:'printing'},{name:'Mecânica',model:'mechanic'},{name:'Pneus',model:'mechanic'},{name:'Cozinha',model:'food'},{name:'Hospedagem',model:'lodging'}];
export type RangeMode='day'|'week'|'month'|'year'|'custom';
const iso=(d:Date)=>d.toISOString().slice(0,10);
export function dateRange(mode:RangeMode,anchor:string,start:string,end:string){const d=new Date(anchor+'T12:00:00Z');if(!Number.isFinite(d.getTime()))return null;let a=new Date(d),b=new Date(d);if(mode==='custom'){a=new Date(start+'T12:00:00Z');b=new Date(end+'T12:00:00Z')}if(mode==='week'){a.setUTCDate(a.getUTCDate()-((a.getUTCDay()+6)%7));b=new Date(a);b.setUTCDate(b.getUTCDate()+6)}if(mode==='month'){a.setUTCDate(1);b=new Date(Date.UTC(a.getUTCFullYear(),a.getUTCMonth()+1,0,12))}if(mode==='year'){a=new Date(Date.UTC(a.getUTCFullYear(),0,1,12));b=new Date(Date.UTC(a.getUTCFullYear(),11,31,12))}if(!Number.isFinite(a.getTime())||!Number.isFinite(b.getTime())||a>b||(b.getTime()-a.getTime())/86400000>3660)return null;return{start:iso(a),end:iso(b)}}
export function financialSeries(entries:any[],range:{start:string;end:string}|null){if(!range)return[];const days=(Date.parse(range.end)-Date.parse(range.start))/86400000;const monthly=days>62;const rows=new Map<string,{day:string;Receitas:number;Despesas:number}>();for(let d=new Date(range.start+'T12:00:00Z');iso(d)<=range.end;d.setUTCDate(d.getUTCDate()+1)){const key=iso(d).slice(0,monthly?7:10);if(!rows.has(key))rows.set(key,{day:monthly?key.slice(5)+'/'+key.slice(0,4):iso(d).slice(8)+'/'+iso(d).slice(5,7),Receitas:0,Despesas:0})}for(const e of entries){if(e.status!=='paid'||e.date<range.start||e.date>range.end)continue;const row=rows.get(e.date.slice(0,monthly?7:10));if(row){if(e.type==='income')row.Receitas+=Number(e.amount);else if(e.type==='expense')row.Despesas+=Number(e.amount)}}return [...rows.values()]}
export type PriceInputs=Record<string,number>;
export const priceDefaults:PriceInputs={material:18.5,hours:2,hourly:25,rent:1800,fixedEnergy:180,otherFixed:300,productiveHours:160,power:150,kwh:0.95,machineHours:5,maintenance:80,monthlyMachineHours:160,grams:120,kgCost:90,loss:5,finishHours:.25,packaging:2,units:12,batchHours:2,nights:3,occupiedNights:20,cleaning:90,daily:15,monthly:1500,purchase:30,freight:4,monthlyUnits:200,fees:12,margin:30};
export function calculatePrice(model:ModelId,v:PriceInputs){if(Object.values(v).some(n=>!Number.isFinite(n)||n<0))return{error:'Preencha valores válidos, iguais ou maiores que zero.',lines:[],cost:0,price:0};if(v.fees+v.margin>=100)return{error:'Taxas e margem precisam somar menos de 100%.',lines:[],cost:0,price:0};let lines:{label:string;value:number}[]=[];const add=(label:string,value:number)=>lines.push({label,value});const fixed=v.rent+v.fixedEnergy+v.otherFixed;
if(model==='printing'){if(!v.monthlyMachineHours||!v.productiveHours)return{error:'Informe as horas produtivas e as horas mensais da máquina.',lines:[],cost:0,price:0};add('Filamento + perda estimada',v.grams/1000*v.kgCost*(1+v.loss/100));add('Energia da impressão',v.power/1000*v.machineHours*v.kwh);add('Manutenção da máquina',v.maintenance/v.monthlyMachineHours*v.machineHours);add('Acabamento e preparo',v.finishHours*v.hourly);add('Aluguel e outros custos rateados',(v.rent+v.otherFixed)/v.monthlyMachineHours*v.machineHours);add('Embalagem',v.packaging)}
if(model==='mechanic'||model==='service'){if(!v.productiveHours)return{error:'Horas produtivas mensais devem ser maiores que zero.',lines:[],cost:0,price:0};add('Peças e materiais',v.material);add('Mão de obra',v.hours*v.hourly);add('Aluguel rateado',v.rent/v.productiveHours*v.hours);add('Energia fixa rateada',v.fixedEnergy/v.productiveHours*v.hours);add('Outras despesas rateadas',v.otherFixed/v.productiveHours*v.hours)}
if(model==='food'){if(!v.units||!v.productiveHours)return{error:'Informe rendimento do lote e horas produtivas.',lines:[],cost:0,price:0};add('Ingredientes + perdas por unidade',v.material*(1+v.loss/100)/v.units);add('Mão de obra por unidade',v.batchHours*v.hourly/v.units);add('Custos fixos por unidade',fixed/v.productiveHours*v.batchHours/v.units);add('Embalagem por unidade',v.packaging)}
if(model==='lodging'){if(!v.nights||!v.occupiedNights)return{error:'Informe noites por estadia e noites ocupadas por mês.',lines:[],cost:0,price:0};add('Custo mensal por noite ocupada',v.monthly/v.occupiedNights);add('Limpeza por noite',v.cleaning/v.nights);add('Consumo e reposições por noite',v.daily)}
if(model==='retail'){if(!v.monthlyUnits)return{error:'Informe a quantidade esperada de vendas mensais.',lines:[],cost:0,price:0};add('Compra por unidade',v.purchase);add('Frete por unidade',v.freight);add('Embalagem',v.packaging);add('Custos fixos por unidade',fixed/v.monthlyUnits)}
const cost=lines.reduce((a,l)=>a+l.value,0);return{error:'',lines,cost,price:cost/(1-(v.fees+v.margin)/100)}}
export const itemLabels:Record<string,string>={finished:'Pronta entrega',material:'Matéria-prima',part:'Peça / componente',service:'Serviço'};
